#apiVersion: v1
#kind: ConfigMap
#metadata:
#  name: simpleconf
#data:
#  xx.yaml: |
#    ip: "0.0.0.0"
#    port: 9092
#    content: "hello from xx.yaml"
#    timeout: 30
#---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: simpleserver
  labels:
    app: simpleserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: simpleserver
  template:
    metadata:
      labels:
        app: simpleserver
    spec:
      terminationGracePeriodSeconds: 32
      containers:
        - name: simpleserver
          image: localhost:5001/http:0.3
          imagePullPolicy: Always
          volumeMounts:
            - name: simpleconf
              mountPath: /conf/xx.yaml
              subPath: data
      volumes:
        - name: simpleconf
          configMap:
            name: simpleconf
---
apiVersion: v1
kind: Service
metadata:
  name: simpleserver
spec:
  selector:
    app: simpleserver
  ports:
    - protocol: TCP
      port: 9090
      targetPort: 9092